site_name: My Docs

repo_url: https://github.com/21km43/21km43.github.io
repo_name: 21km43/21km43.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  language: ja
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.footer
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home:
    - index.md
  - Blog:
    - blog/index.md
  - About:
    - about.md
  - Links:
    - links.md
  # TODO: Flutter Application

not_in_nav: |
  /privacy-policy.md
  /sandbox.md
  

plugins:
  - blog
  - search:
      lang: ja

markdown_extensions:
  - tables
  - def_list
  - admonition
  - attr_list
  - md_in_html

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/21km43
    - icon: fontawesome/brands/github
      link: https://github.com/21km43
  
  analytics:
    provider: google
    property: G-BPQQ2G5K77

  generator: false

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css

copyright: Copyright &copy; 2023 Koki Mizumoto
