/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {  
  sidebar_tutorial_extras: [
    {type: 'link', label: '← 戻る',  href: '..'},
    {type: 'autogenerated', dirName: 'tutorial-extras'},
  ],

  sidebar_tutorial_basics: [
    {type: 'link', label: '← 戻る',  href: '..'},
    {type: 'autogenerated', dirName: 'tutorial-basics'},
  ],
};

module.exports = sidebars;
